version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TZ=America/Sao_Paulo
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=banco
    depends_on:
      - db
    command: npm run dev # rodar nodemon no modo dev

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
